### ISSUE TITLE
link broken -- get 404 on Towards Explainable Multi-modal Motion Prediction using Graph Representations

### ISSUE THREAD

**Issue by Rick-Majpruz** [sancarlim/Explainable-MP#1]
On repo main page at https://github.com/sancarlim/Explainable-MP
the link for ["Towards Explainable Multi-modal Motion Prediction using Graph Representations"](https://github.com/sancarlim/Explainable-MP/blob/main) is broken.

I get "Page not found · GitHub" title with that puzzled octocat image saying: 404 This is not the webpage you are looking for.

**Comment by majsylw** [comment]
Hi Rick-Majpruz ;-)
The link is fixed now and pointed at arxiv preprint of the work.
Sylwia
