### ISSUE TITLE
The visualize can't find the File [Errno 2] No such file or directory: '/media/14TBDISK/sandra//DBU_Graph/NuScenes/icons/Car TOP_VIEW ROBOT.png'

### ISSUE THREAD

**Issue by mishengshisan** [sancarlim/Explainable-MP#3]
When I run the visualize , there show FileNotFoundError: [Errno 2] No such file or directory: '/media/14TBDISK/sandra//DBU_Graph/NuScenes/icons/Car TOP_VIEW ROBOT.png'
and what are these three files:ego_car = plt.imread('/media/14TBDISK/sandra//DBU_Graph/NuScenes/icons/Car TOP_VIEW ROBOT.png')
agent = plt.imread('/media/14TBDISK/sandra/DBU_Graph/NuScenes/icons/Car TOP_VIEW 375397.png')
cars = plt.imread('/media/14TBDISK/sandra/DBU_Graph/NuScenes/icons/Car TOP_VIEW 80CBE5.png') 
thanks

**Comment by sancarlim** [comment]
Thank you for spotting the issue. It has now been resolved.
